#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          NodeServer
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     3 5
# Default-Stop:      0 1 6
# Short-Description: NodeServer Init Script
# Description:       NodeServer Init Script by Simon Schneider sim@raynigon.com
### END INIT INFO

# Author: Simon Schneider <sim@raynigon.com>

NAME="NodeServer"
DESC="NodeServer Init Script"
DAEMON=/usr/bin/nodejs
PIDFILE=/var/run/$NAME.pid
NODE_SCRIPT="/srv/nodejs/website/simpleServer.js"
NODE_DIRECTORY="/srv/nodejs/"

USER="nodejs"
GROUP="www-data"

do_start()
{
	echo -n "Starting daemon: "$NAME
	start-stop-daemon --background --quiet --start --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $NODE_SCRIPT > /dev/null
	echo "."
}

do_stop()
{
	echo -n "Stopping daemon: "$NAME
	start-stop-daemon --stop --quiet --pidfile $PIDFILE > /dev/null
    	echo "."
}

do_status()
{
	echo -n $NAME" Status:"
	start-stop-daemon --verbose --status --pidfile $PIDFILE > /dev/null
	if [ $? = 0 ] 
	then echo "RUNNING" 
	else echo "NOT RUNNING"
	fi
}

case "$1" in
  start)
       do_start
	;;
  stop)
        do_stop
	;;
  restart)
	do_stop
	do_start
	;;
  status)
  	do_status
	;;
  *)
	echo "Usage: "$1" {start|stop|status|restart}"
	exit 1
esac

exit 0